version: '3'
services:
  bot:
    tty: true
    container_name: bot
    restart: unless-stopped
    volumes:
      - .:/opt/bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"
    external: false